server:
  port: 8083   # порт для cart-service

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cart_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # для разработки можно update, в проде лучше validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Если используешь Eureka Discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
