spring:
<<<<<<< HEAD
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: orion
=======
  application:
    name: user-service   # совпадает с user-service.yml в config-repo
>>>>>>> d6a43440dc21285200505b4fd73a5dcdb146be92

  config:
    import: "configserver:http://localhost:8888"

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
