server:
  port: 8761   # стандартный порт для Eureka

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false   # сам сервер не регистрируется
    fetch-registry: false
